#!/bin/bash

today=$(date +"%Y%m%d")
releasever=$1
target=$2
title=Hawaii
product=hawaii

if [ -z "$releasever" -o -z "$target" ]; then
    echo "Usage: $0 <releasever> <target>"
    exit 1
fi

if [ ! -f hawaii-${target}.ks ]; then
    echo "Invalid target ${target}"
    exit 1
fi

kspath=/tmp/hawaii-appliance-$$.ks
ksflatten -c hawaii-${target}.ks -o $kspath || exit 1

sudo appliance-creator -c $kspath -n $title --version=$today --checksum -dv --logfile=appliance.log

rm -f $kspath
