#!/bin/bash

curdir=`dirname $(readlink -f $0)`

today=$(date +"%Y%m%d")
target=$1
title="Liri OS"
product="lirios"

source $curdir/.settings

if [ -z "$releasever" ]; then
    echo "Fedora release not specified, please check your .settings"
    exit 1
fi

if [ -z "$target" ]; then
    echo "Usage: $0 <target>"
    exit 1
fi

if [ ! -f ${product}-${target}.ks ]; then
    echo "Invalid target ${target}"
    exit 1
fi

kspath=/tmp/${product}-appliance-$$.ks
ksflatten -c ${product}-${target}.ks -o $kspath || exit 1

sudo appliance-creator -c $kspath -n $title --version=$today --checksum -dv --logfile=appliance.log

rm -f $kspath
